export const boardBrands = [
  "AIPA",
  "Album Surfboards",
  "Aloha",
  "Almond Surfboards",
  "Andreini Surfboards",
  "Arakawa Surfboards",
  "Avocado Surfboards",
  "Bear Surfboards",
  "Bear USA",
  "BIC Sport Surfboards",
  "Bing",
  "CBC (California Board Company)",
  "Cabianca Surfboards",
  "Campbell Brothers (Bonzer)",
  "Catch Surf",
  "Channel Islands / Al Merrick",
  "Chemistry Surfboards",
  "Chilli Surfboards",
  "Christenson Surfboards",
  "Creative Army Surfboards",
  "DHD Surfboards",
  "DMS Surfboards",
  "DVS Surfboards",
  "Dead Kooks",
  "Degree 33 Surfboards",
  "Donald Takayama",
  "Earth Technologies",
  "Emery Surfboards",
  "Eye Symmetry Surfboards",
  "Firewire",
  "Formula Energy",
  "G&S (Gordon & Smith)",
  "Gary McNeill Concepts",
  "Gato Heroi",
  "Gerry Lopez Surfboards",
  "Gordon & Smith",
  "Greg Noll",
  "Hawaiian Island Creations (HIC)",
  "Hayden Shapes",
  "Hobie",
  "Hot Buttered (HB)",
  "INF Softboards",
  "Infinity Surfboards",
  "Iron Cross Surfboards",
  "JS Industries",
  "JR Surfboards",
  "Kazuma Surfboards",
  "Lib Tech",
  "Liquid Shredder",
  "Lost Surfboards by Mayhem",
  "Lost x Carver",
  "Mark Richards Surfboards",
  "Maurice Cole",
  "McTavish",
  "Mick Fanning Softboards",
  "Misfit Shapes",
  "Modern Surfboards",
  "Modern Twin Surfboards",
  "MT Woodgee Surfboards",
  "Nick Blair / Joistik Surfboards",
  "Nineplus",
  "NSP",
  "NSP Protech",
  "Ocean & Earth",
  "Olaian",
  "Paragon Surfboards",
  "Pavel Surfboards",
  "Pukas",
  "Pyzel",
  "Quiet Flight",
  "Quiksilver",
  "Rawson Surfboards",
  "Rip Curl",
  "Rusty",
  "Ryan Lovelace Surf Craft",
  "Savage Surfboards",
  "Sharp Eye",
  "Simon Anderson Surfboards",
  "Skindog Surfboards",
  "Slater Designs",
  "Softech",
  "South Bay Board Co.",
  "Spider Murphy / Safari Surf",
  "Stacey Surfboards",
  "Stewart Surfboards",
  "Stormblade",
  "Stretch Surfboards",
  "Subtech",
  "Sunova",
  "Superbrand",
  "Surftech",
  "Takayama Surfboards",
  "Takeda Customs",
  "Thomas Surfboards",
  "Tomo Surfboards",
  "Torq",
  "Town and Country (T&C)",
  "Town & Country Surf Designs Japan",
  "Tyler Surfboards",
  "Tyler Warren Shapes",
  "Varley Surfboards",
  "Vega Surfboards",
  "Vessel Surfboards",
  "Vouch Surfboards",
  "Wavestorm",
  "Wavex",
];
